# web port
server:
  port: ${PORT:}

# log config
logging:
  config: classpath:logback.xml
  path: ${data.path:/home/}/applogs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
#      addresses: http://${DATAX_ADMIN_HOST:127.0.0.1}:${DATAX_ADMIN_PORT:9527}
      addresses: ${ADDRESSES:}
    executor:
      appname: datax-executor
      ip:
      port: ${executor.port:9999}
      ### job log path
      logpath: ${data.path:/home}/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:
    yarn:
      run: false
      client-jar: ${data.path:/home}/applogs/executor/jobhandler/datax-on-yarn.jar
      hdfs-tar: /hadoop/datax.tar.gz
      queue: default
      memory: 1024
  executor:
    jsonpath: ${json.path:/opt/datax-web-2.1.3/modules/datax-executor/json}
    pythonpath: python

  pypath: ${python.path:/opt/datax/bin/datax.py}
